### ISSUE TITLE
Sir,if the nearest neighbors always be a few of the embeddings

### ISSUE THREAD

**Issue by jiqizaisikao** [nadavbh12/VQ-VAE#1]
Hi,i have run your code,it seems right,but i have one question:because embeddings are inited randomly and there seems no guarantee not always to select a few of the embeddings。So is there and guarantee to make sure that as many as  embeddings being used?

**Comment by nadavbh12** [comment]
That's correct. There's no explicit guarantee or regularization to use all embedding.
The implicit regularization may be a high MSE.
Perhaps an orthogonal initialization to the dictionary may reduce the chance for this.
Another alternative is to add some regularization the penalizes for not using all embeddings.
