### ISSUE TITLE
a small bug in the code

### ISSUE THREAD

**Issue by zhangfuyang** [nadavbh12/VQ-VAE#10]
Hi, thanks for your awesome code! 
When I try to run the VQ_CVAE model (imagenet), I find there is an error.

In vq_vae/nearest_embed.py, line 53. A comma is missed. I believe it should be `argmin, = ctx.saved_variables`.

I tested in torch 1.2.0 as well as 0.4. Both have this issue.

Anyway, great work! thank you so much!

**Comment by nadavbh12** [comment]
Thanks for the words and fix! I've pushed an update.
