### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by zhangbo2008** [nadavbh12/VQ-VAE#14]
return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1

**Comment by samuelkim314** [comment]
Replace

`        return self.tanh(self.fc4(h3))`

in line 81 with

`        return self.sigmoid(self.fc4(h3))`

**Comment by zhangbo2008** [comment]
yep



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Samuel ***@***.***> |
| Date | 11/10/2022 01:29 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [nadavbh12/VQ-VAE] a bug (#14) |

Replace

return self.tanh(self.fc4(h3))

in line 81 with

return self.sigmoid(self.fc4(h3))
