### ISSUE TITLE
Is is wrong for your code?

### ISSUE THREAD

**Issue by jiqizaisikao** [nadavbh12/VQ-VAE#2]
The encoder should output a D dim vector,not a (KxD)vector, the K is the number of D vector in the disc.

**Comment by jiqizaisikao** [comment]
And you should not use fc layer yet ,instead you should use a conv layer ,there is no reason to use a fc layer

**Comment by nadavbh12** [comment]
The encoder output is of dimension emb_dim x d x d where d is the reduced image size after convs.
In the [VQ-CVAE](https://github.com/nadavbh12/VQ-VAE/blob/master/auto_encoder.py#L255), you can see that k=16 and emb_dim=d (256).

FC layer I'm guessing you're referring to the [CVAE](https://github.com/nadavbh12/VQ-VAE/blob/master/auto_encoder.py#L184). I believe both FC and conv are valid. I arbitrarily chose FC.
Couldn't find any reference for a CVAE comparing them (or any CVAE actually).

**Comment by jiqizaisikao** [comment]
I see, i misunderstood it,as the paper's title says,the discrete vector just represent one representation,if the encoder output only have D dimension,then the decoder output always be the same,it is one same dot。
